name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Get Version
        id: version
        run: |
          echo "version=$(node -p "require('./manifest.json').version")" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Check Version Match
        run: |
          if [ "${{ steps.version.outputs.version }}" != "${{ steps.version.outputs.tag }}" ]; then
            echo "Version in manifest.json (${{ steps.version.outputs.version }}) does not match tag (${{ steps.version.outputs.tag }})"
            exit 1
          fi

      - name: Install Dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          
          # 创建发布文件列表
          files=("main.js" "manifest.json")
          if [ -f "styles.css" ]; then
            files+=("styles.css")
          fi
          
          # 创建发布
          gh release create "$tag" \
            --title="$tag" \
            --draft \
            "${files[@]}"
